import React from 'react';
import { 
  X, 
  CheckCircle2, 
  Clock, 
  ArrowRight, 
  ShieldAlert, 
  UserCheck, 
  ClipboardCheck, 
  Download,
  Building2,
  FileCheck2
} from 'lucide-react';
import { ActionPlanItem, Mine } from '../types';

interface ActionPlanModalProps {
  isOpen: boolean;
  onClose: () => void;
  mine: Mine;
  actionPlan: ActionPlanItem[];
  onDispatchInspection: (mineId: string) => void;
}

export const ActionPlanModal: React.FC<ActionPlanModalProps> = ({
  isOpen,
  onClose,
  mine,
  actionPlan,
  onDispatchInspection
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-in fade-in duration-150">
      <div className="bg-white rounded-2xl shadow-2xl border border-slate-200 w-full max-w-2xl overflow-hidden animate-in zoom-in-95 duration-200 flex flex-col max-h-[90vh]">
        
        {/* Header */}
        <div className="p-5 border-b border-slate-200 bg-slate-900 text-white flex items-start justify-between">
          <div>
            <div className="flex items-center gap-2 text-xs font-bold text-blue-400 uppercase tracking-wider">
              <span>AI Mitigative Governance Blueprint</span>
              <span>·</span>
              <span>DGMS Fast-Track</span>
            </div>
            <h2 className="text-xl font-black text-white mt-1">
              Statutory Action Plan: {mine.name}
            </h2>
            <p className="text-xs text-slate-300 mt-0.5">
              Automated high-priority remediation measures generated by CoalGuard AI Risk Engine.
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 overflow-y-auto space-y-4">
          
          <div className="p-3.5 bg-blue-50 border border-blue-200 rounded-xl text-xs text-blue-900 flex items-center justify-between">
            <div>
              <span className="font-bold">Remediation Target:</span>
              <span className="ml-1">Reduce current composite hazard score from {mine.riskScore}/100 to &lt; 40 within 7 calendar days.</span>
            </div>
            <span className="text-[10px] font-bold uppercase bg-blue-200 text-blue-900 px-2 py-0.5 rounded">
              Priority Sequence
            </span>
          </div>

          <div className="space-y-3.5">
            {actionPlan.map((item) => (
              <div 
                key={item.priority}
                className="p-4 rounded-xl border border-slate-200 bg-white hover:border-blue-300 transition-colors shadow-2xs"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="w-6 h-6 rounded-full bg-blue-700 text-white font-black text-xs flex items-center justify-center">
                      {item.priority}
                    </span>
                    <h3 className="text-sm font-bold text-slate-900">
                      Priority {item.priority}: {item.title}
                    </h3>
                  </div>
                  <span className="text-[11px] font-bold text-red-600 bg-red-50 px-2 py-0.5 rounded">
                    {item.timeline}
                  </span>
                </div>

                <p className="text-xs text-slate-700 mt-2 leading-relaxed">
                  {item.description}
                </p>

                <div className="mt-3 pt-2.5 border-t border-slate-100 grid grid-cols-1 sm:grid-cols-2 gap-2 text-[11px]">
                  <div>
                    <span className="text-slate-400 font-semibold uppercase text-[10px]">Assignee:</span>
                    <div className="text-slate-800 font-medium">{item.assignee}</div>
                  </div>
                  <div>
                    <span className="text-slate-400 font-semibold uppercase text-[10px]">Statutory Impact:</span>
                    <div className="text-emerald-700 font-medium">{item.impact}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>

        </div>

        {/* Footer Actions */}
        <div className="p-4 border-t border-slate-200 bg-slate-50 flex items-center justify-between">
          <button
            onClick={onClose}
            className="px-3.5 py-2 text-xs font-semibold text-slate-600 hover:text-slate-800 transition-colors"
          >
            Dismiss
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={() => {
                onClose();
                onDispatchInspection(mine.id);
              }}
              className="px-4 py-2 text-xs font-bold text-white bg-blue-700 hover:bg-blue-800 rounded-lg shadow-sm transition-colors flex items-center gap-1.5"
            >
              <ClipboardCheck className="w-4 h-4 text-blue-200" />
              <span>Proceed to Field Inspection Form</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
